shell.run("cd /")
shell.run("mkdir pid")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/config.lua /pid/config.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20up.lua /pid/pidup.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20down.lua /pid/piddown.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20left.lua /pid/pidleft.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20right.lua /pid/pidright.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20front.lua /pid/pidfront.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20back.lua /pid/pidback.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20rleft.lua /pid/pidrleft.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20rright.lua /pid/pidrright.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20main.lua /pid/pidmain.lua")
print("Done!")
print("launch /pid/pidmain")
