shell.run("cd /")
shell.run("mkdir pid")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/config.lua /pid/config.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20up.lua /pid/up.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20down.lua /pid/down.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20left.lua /pid/left.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20right.lua /pid/right.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20front.lua /pid/front.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20back.lua /pid/back.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20rleft.lua /pid/rleft.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20rright.lua /pid/rright.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20main.lua /pid/main.lua")
print("Done!")