shell.run("cd /")
shell.run("mkdir pid")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/config.lua /pid/config.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20up.lua /pid/pid up.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20down.lua /pid/pid down.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20left.lua /pid/pid left.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20right.lua /pid/pid right.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20front.lua /pid/pid front.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20back.lua /pid/pid back.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20rleft.lua /pid/pid rleft.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20rright.lua /pid/pid rright.lua")
shell.run("wget https://raw.githubusercontent.com/FilkteZ/filnix/main/pid%20main.lua /pid main.lua")
print("Done!")